/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all regions. */
        get: operations["region_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces. */
        get: operations["workspace_list"];
        put?: never;
        /** Create workspace. */
        post: operations["workspace_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workspace. */
        get: operations["workspace_get"];
        /** Update workspace. */
        put: operations["workspace_update"];
        post?: never;
        /** Delete workspace. */
        delete: operations["workspace_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_name}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices. */
        get: operations["device_list"];
        put?: never;
        /** Create device. */
        post: operations["device_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_name}/devices/{device_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get device. */
        get: operations["device_get"];
        /** Update device. */
        put: operations["device_update"];
        post?: never;
        /** Delete device. */
        delete: operations["device_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_name}/gateways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gateways. */
        get: operations["gateway_list"];
        put?: never;
        /** Create gateway. */
        post: operations["gateway_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_name}/gateways/{gateway_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get gateway. */
        get: operations["gateway_get"];
        /** Update gateway. */
        put: operations["gateway_update"];
        post?: never;
        /** Delete gateway. */
        delete: operations["gateway_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_name}/gateways/{gateway_name}/allow-key-exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set allow key exchange through gateway. */
        post: operations["gateway_allow_key_exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @description Error message describing what went wrong */
            message: string;
        };
        Device: {
            /**
             * Format: date-time
             * @description Last activation at timestamp.
             * @default null
             */
            activation_at: string | null;
            configuration?: unknown;
            configuration_wanted?: unknown;
            /**
             * Format: date-time
             * @description Created-at timestamp.
             * @default 2026-07-23T10:01:50.750833617Z
             */
            created_at: string;
            /**
             * @description Description of the device.
             * @default
             */
            description: string;
            /**
             * Format: date-time
             * @description Last key-exchange timestamp.
             * @default null
             */
            key_exchange_at: string | null;
            /**
             * @description Name.
             *     Valid input is a-z, A-Z, 0-9 and -, e.g. test-device-123.
             * @default
             */
            name: string;
            /** @default 00000000 */
            pin: components["schemas"]["HEX string"];
            /** @default 0000 */
            profile_id: components["schemas"]["HEX string"];
            /** @default 0000000000000000000000000000000000000000000000000000000000000000 */
            public_key: components["schemas"]["HEX string"];
            /** @default 00000000 */
            short_id: components["schemas"]["HEX string"];
            state?: unknown;
            state_wanted?: unknown;
            telemetry?: unknown;
            /**
             * Format: date-time
             * @description Updated-at timestamp.
             * @default 2026-07-23T10:01:50.750836382Z
             */
            updated_at: string;
            /** @default 00000000 */
            vendor_id: components["schemas"]["HEX string"];
            /** @default  */
            vendor_name: string;
            /** @default 0000 */
            version_id: components["schemas"]["HEX string"];
        };
        Gateway: {
            /**
             * Format: date-time
             * @description Allow key-exchange requests until given timestamp.
             * @default null
             */
            allow_key_exchange_until: string | null;
            /**
             * Format: date-time
             * @description Created-at timestamp.
             * @default 1970-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * @description Description.
             * @default
             */
            description: string;
            /**
             * Format: date-time
             * @description Last heartbeat timestamp.
             * @default null
             */
            last_heartbeat_at: string | null;
            /**
             * @description Name.
             *     Valid characters are a-z, A-Z, 0-9 and -. Example: test-gateway-123.
             * @default
             */
            name: string;
            /**
             * @description Region module.
             * @default
             */
            region_module: string;
            /**
             * Format: date-time
             * @description Updated-at timestamp.
             * @default 1970-01-01T00:00:00Z
             */
            updated_at: string;
        };
        GatewayAllowKeyExchangeRequest: {
            /** @description Duration in seconds. */
            duration_sec: number;
        };
        "HEX string": string;
        ListResponse_Device: {
            result: {
                /**
                 * Format: date-time
                 * @description Last activation at timestamp.
                 * @default null
                 */
                activation_at: string | null;
                configuration?: unknown;
                configuration_wanted?: unknown;
                /**
                 * Format: date-time
                 * @description Created-at timestamp.
                 * @default 2026-07-23T10:01:50.750867591Z
                 */
                created_at: string;
                /**
                 * @description Description of the device.
                 * @default
                 */
                description: string;
                /**
                 * Format: date-time
                 * @description Last key-exchange timestamp.
                 * @default null
                 */
                key_exchange_at: string | null;
                /**
                 * @description Name.
                 *     Valid input is a-z, A-Z, 0-9 and -, e.g. test-device-123.
                 * @default
                 */
                name: string;
                /** @default 00000000 */
                pin: components["schemas"]["HEX string"];
                /** @default 0000 */
                profile_id: components["schemas"]["HEX string"];
                /** @default 0000000000000000000000000000000000000000000000000000000000000000 */
                public_key: components["schemas"]["HEX string"];
                /** @default 00000000 */
                short_id: components["schemas"]["HEX string"];
                state?: unknown;
                state_wanted?: unknown;
                telemetry?: unknown;
                /**
                 * Format: date-time
                 * @description Updated-at timestamp.
                 * @default 2026-07-23T10:01:50.750869224Z
                 */
                updated_at: string;
                /** @default 00000000 */
                vendor_id: components["schemas"]["HEX string"];
                /** @default  */
                vendor_name: string;
                /** @default 0000 */
                version_id: components["schemas"]["HEX string"];
            }[];
            total_count: number;
        };
        ListResponse_Gateway: {
            result: {
                /**
                 * Format: date-time
                 * @description Allow key-exchange requests until given timestamp.
                 * @default null
                 */
                allow_key_exchange_until: string | null;
                /**
                 * Format: date-time
                 * @description Created-at timestamp.
                 * @default 1970-01-01T00:00:00Z
                 */
                created_at: string;
                /**
                 * @description Description.
                 * @default
                 */
                description: string;
                /**
                 * Format: date-time
                 * @description Last heartbeat timestamp.
                 * @default null
                 */
                last_heartbeat_at: string | null;
                /**
                 * @description Name.
                 *     Valid characters are a-z, A-Z, 0-9 and -. Example: test-gateway-123.
                 * @default
                 */
                name: string;
                /**
                 * @description Region module.
                 * @default
                 */
                region_module: string;
                /**
                 * Format: date-time
                 * @description Updated-at timestamp.
                 * @default 1970-01-01T00:00:00Z
                 */
                updated_at: string;
            }[];
            total_count: number;
        };
        ListResponse_RegionListItem: {
            result: {
                /** @description Module. */
                module: string;
                /** @description Name. */
                name: string;
            }[];
            total_count: number;
        };
        ListResponse_Workspace: {
            result: {
                /**
                 * Format: date-time
                 * @description Created-at timestamp.
                 * @default 1970-01-01T00:00:00Z
                 */
                created_at: string;
                /**
                 * @description Description.
                 * @default
                 */
                description: string;
                /**
                 * @description Name.
                 *     Valid characters are a-z, A-Z, 0-9 and -. Example: test-workspace-123.
                 * @default
                 */
                name: string;
                /**
                 * Format: date-time
                 * @description Updated-at timestamp.
                 * @default 1970-01-01T00:00:00Z
                 */
                updated_at: string;
            }[];
            total_count: number;
        };
        RegionListItem: {
            /** @description Module. */
            module: string;
            /** @description Name. */
            name: string;
        };
        Workspace: {
            /**
             * Format: date-time
             * @description Created-at timestamp.
             * @default 1970-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * @description Description.
             * @default
             */
            description: string;
            /**
             * @description Name.
             *     Valid characters are a-z, A-Z, 0-9 and -. Example: test-workspace-123.
             * @default
             */
            name: string;
            /**
             * Format: date-time
             * @description Updated-at timestamp.
             * @default 1970-01-01T00:00:00Z
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    region_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_RegionListItem"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    workspace_list: {
        parameters: {
            query?: {
                /** @description The offset in the result set. */
                offset?: number;
                /** @description The number of items to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_Workspace"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    workspace_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Workspace"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    workspace_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Workspace"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    workspace_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    device_list: {
        parameters: {
            query?: {
                /** @description The offset in the result set. */
                offset?: number;
                /** @description The number of items to return. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_Device"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    device_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Device"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    device_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
                /** @description Device name. */
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    device_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
                /** @description Device name. */
                device_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Device"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    device_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
                /** @description Device name. */
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gateway_list: {
        parameters: {
            query?: {
                /** @description The offset in the result set. */
                offset?: number;
                /** @description The number of items to return. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_Gateway"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gateway_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace name. */
                workspace_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Gateway"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gateway_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace ID. */
                workspace_name: string;
                /** @description Gateway ID. */
                gateway_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gateway"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gateway_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace ID. */
                workspace_name: string;
                /** @description Gateway ID. */
                gateway_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Gateway"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gateway_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace ID. */
                workspace_name: string;
                /** @description Gateway ID. */
                gateway_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gateway_allow_key_exchange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace ID. */
                workspace_name: string;
                /** @description Gateway ID. */
                gateway_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayAllowKeyExchangeRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
