MEMORY {
  BOOT2         : ORIGIN = 0x10000000, LENGTH = 0x100
  FLASH         : ORIGIN = ORIGIN(BOOT2) + LENGTH(BOOT2), LENGTH = 2048K - LENGTH(BOOT2) - 8K
  ROOT_SECURITY : ORIGIN = ORIGIN(FLASH) + LENGTH(FLASH), LENGTH = 4K
  COUNTERS      : ORIGIN = ORIGIN(ROOT_SECURITY) + LENGTH(ROOT_SECURITY), LENGTH = 4K 
  RAM           : ORIGIN = 0x20000000, LENGTH = 264K
}

__root_security_start = ORIGIN(ROOT_SECURITY) - ORIGIN(BOOT2);
__root_security_end   = ORIGIN(ROOT_SECURITY) + LENGTH(ROOT_SECURITY) - ORIGIN(BOOT2);

__counters_start      = ORIGIN(COUNTERS) - ORIGIN(BOOT2);
__counters_end        = ORIGIN(COUNTERS) + LENGTH(COUNTERS) - ORIGIN(BOOT2);

